In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
data = pd.read_csv('sonar_dataset.csv', header=None)
data.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [3]:
data.shape

(208, 61)

In [4]:
data.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [5]:
data.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [6]:
x = data.drop(60, axis=1)
x.shape

(208, 60)

In [7]:
y = data[60]
y.sample(5)

136    M
198    M
79     R
180    M
106    M
Name: 60, dtype: object

In [8]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5)

R
187  0
193  0
200  0
67   1
10   1

In [9]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [10]:
x.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [12]:
x_train.shape, x_test.shape

((156, 60), (52, 60))

In [13]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(60, input_shape=(60,), activation='relu'),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(15, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 3ms/step - loss: 0.6763 - accuracy: 0.5641
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6500 - accuracy: 0.6346
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6273 - accuracy: 0.6667
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5900 - accuracy: 0.7115
Epoch 5/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5463 - accuracy: 0.7244
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5134 - accuracy: 0.7949
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4819 - accuracy: 0.7885
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4555 - accuracy: 0.8269
Epoch 9/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4330 - accuracy: 0.8269
Epoch 10/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4487 - accuracy: 0.7885
Epoch 11/

In [14]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 5ms/step - loss: 1.2378 - accuracy: 0.7308


[1.2378499507904053, 0.7307692170143127]

In [15]:
y_pred = model.predict(x_test).reshape(-1)
y_pred.shape

(52,)

In [16]:
y_pred[:10]

array([4.2658232e-07, 9.8788548e-01, 9.9682331e-01, 6.7158908e-05,
       1.0000000e+00, 9.9999249e-01, 9.3880427e-01, 1.0000000e+00,
       3.7974325e-05, 1.0000000e+00], dtype=float32)

In [17]:
y_pred = np.round(y_pred)
y_pred[:10]

array([0., 1., 1., 0., 1., 1., 1., 1., 0., 1.], dtype=float32)

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.81      0.76        27
           1       0.76      0.64      0.70        25

    accuracy                           0.73        52
   macro avg       0.74      0.73      0.73        52
weighted avg       0.73      0.73      0.73        52



## Having a Dropout Layer after each Hidden Layer

In [25]:
model_drop = tf.keras.Sequential([
    tf.keras.layers.Dense(60, input_shape=(60,), activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(15, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model_drop.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_drop.fit(x_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7008 - accuracy: 0.5897
Epoch 2/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7256 - accuracy: 0.5128
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6921 - accuracy: 0.5513
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6780 - accuracy: 0.5256
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6839 - accuracy: 0.5705
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6724 - accuracy: 0.5833
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6822 - accuracy: 0.5641
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6819 - accuracy: 0.5833
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6540 - accuracy: 0.6090
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6632 - accuracy: 0.5833
Epoch 11/

In [26]:
model_drop.evaluate(x_test, y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.5650 - accuracy: 0.7692


[0.5650002360343933, 0.7692307829856873]

*When we apply dropout layer then we drop 'x' percent of the neurons on that hidden layer at random. This is done at every training step.*

**Here accuracy on test dataset increased from 73.07 to 76.92**

In [32]:
y_pred_drop = model_drop.predict(x_test).reshape(-1)
y_pred_drop[:10]

array([2.6849950e-05, 9.6230918e-01, 9.0663505e-01, 9.1303885e-03,
       9.9994683e-01, 9.2818105e-01, 4.7783250e-01, 9.9991214e-01,
       5.4365993e-03, 9.9998510e-01], dtype=float32)

In [33]:
y_pred_drop = np.round(y_pred_drop)
y_pred_drop[:10]

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [34]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [35]:
print(classification_report(y_test, y_pred_drop))

              precision    recall  f1-score   support

           0       0.74      0.85      0.79        27
           1       0.81      0.68      0.74        25

    accuracy                           0.77        52
   macro avg       0.78      0.77      0.77        52
weighted avg       0.77      0.77      0.77        52

